### api end point for user 
@url =http://localhost:3002/api/v1/users/register
POST {{url}}
Content-Type: application/json

{
  "Fname": "John",
  "Lname": "Doe",
  "email": "1@5",
  "passwordHashed":"111"
}
### get user for login
@getUrl = http://localhost:3002/api/v1/users/login
POST {{getUrl}}
Content-Type: application/json


{
 
  "email": "1@1",
  "passwordHashed":"111"
}

### get user profile
GET  http://localhost:3002/api/v1/users
Content-Type: application/json
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IjFAOCIsImlhdCI6MTcyODIwMTMzNSwiZXhwIjoxNzI4MjAxMzk1fQ.3tFheiftkmms3Z5UOeKIGwWv_s5ww3KnfT5-ZZJV2CI



### Post new transaction
POST http://localhost:3002/api/v1/transactions/addtransaction
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IjFAMSIsImlhdCI6MTcyODUyNDM5MSwiZXhwIjoxNzI4NTI3OTkxfQ.6SqP0WQiZDhQlvMtVJ9yjFCJoeeR5pR6xKUpLM0oceU



{
  "Tittle": "salary",
    "type":"income",
   "UserId":"66fbc3b1c41ff4e0f285ab46",
   "amount":100,
   "TransactionDate":"2012-07-01"
    }

### get transaction
GET  http://localhost:3002/api/v1/transactions
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IjFAMSIsImlhdCI6MTcyODUyNDM5MSwiZXhwIjoxNzI4NTI3OTkxfQ.6SqP0WQiZDhQlvMtVJ9yjFCJoeeR5pR6xKUpLM0oceU

### delete transaction
DELETE   http://localhost:3002/api/v1/transactions/deleteTransactins
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IjFAMSIsImlhdCI6MTcyOTU5MTg1OSwiZXhwIjoxNzI5NTk1NDU5fQ.no4HuUfzvp36wFy643WWe2f9V_ED4f8Ak3MHvyeF1BM




























