### api end point for user 
@url =http://localhost:3000/api/v1/users/register
POST {{url}}
Content-Type: application/json

{
  "Fname": "John",
  "Lname": "Doe",
  "email": "1@1",
  "passwordHashed":"111"
}
### get user for login
@getUrl = http://localhost:3000/api/v1/users/login
POST {{getUrl}}
Content-Type: application/json


{
 
  "email": "1@1",
  "passwordHashed":"111"
}

### get user profile
GET  http://localhost:3000/api/v1/users
Content-Type: application/json
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IjFAMSIsImlhdCI6MTcyNzY5NTc5NH0.4SYUEasYDw-J8Hxi4T7rrcQ3Nc45z-_mc8wr-Mp2KRg